function sofaDataFn() {


    var sofaData = [
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202152/0492/dream-square-arm-upholstered-sofa-3-l.jpg",
          name: "Dream Square Arm Upholstered Sofa",
          price: 1999,
          rating: 4.9,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(40)",
          product: "blush",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 5,
          count: 1,
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202203/1015/dream-square-arm-slipcovered-sofa-collection-4-l.jpg",
          name: "Dream Square Arm Slipcovered Sofa",
          price: 2099,
          rating: 4.7,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(5)",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 7,
          count: 1,
          product: "blush",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202152/0492/dream-square-arm-upholstered-modular-sofa-chaise-sectional-1-c.jpg",
          name: "Dream Square Arm Upholstered Modular Sofa Chaise Sectional",
          price: 5196,
          rating: 4.7,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(20)",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 11,
          count: 1,
          product: "",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202151/1486/dream-square-arm-splicovered-modular-sofa-l.jpg",
          name: "Dream Square Arm Slipcovered Modular Sofa Chaise Sectional",
          price: 5596,
          rating: 4.7,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(10)",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 4,
          count: 1,
          product: "matte",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202152/0492/dream-square-arm-upholstered-modular-l-shaped-sectional-2-l.jpg",
          name: "Dream Square Arm Upholstered Modular L-Shaped Sectional",
          price: 7045,
          rating: 4.9,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(45)",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 20,
          count: 1,
          product: "Matte",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202152/0902/dream-square-arm-slipcovered-modular-l-shaped-sectional-l.jpg",
          name: "Dream Square Arm Slipcovered Modular L-Shaped Sectional",
          price: 7845,
          rating: 4.7,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(20)",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 8,
          count: 1,
          product: "eye",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202152/1334/dream-square-arm-upholstered-3-piece-l-shaped-sectional-3-c.jpg",
          name: "Dream Square Arm Upholstered 3-Piece L-Shaped Sectional",
          price: 5747,
          rating: 4.7,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(15)",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 5,
          count: 1,
          product: "crayon",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202152/1331/dream-square-arm-splipcovered-modular-3-piece-l-shaped-sec-l.jpg",
          name: "Dream Square Arm Slipcovered 3-Piece L-Shaped Sectional",
          price: 6047,
          rating: 4.5,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(2)",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 12,
          count: 1,
          product: "liquid",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202152/1334/dream-square-arm-upholstered-3-piece-corner-sectional-l.jpg",
          name: "Dream Square Arm Upholstered 3-Piece Corner Sectional",
          price: 5047,
          rating: 4.8,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(50)",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 5,
          count: 1,
          product: "found",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202152/1331/dream-square-arm-slipcovered-3-piece-corner-sectional-2-c.jpg",
          name: "Dream Square Arm Slipcovered 3-Piece Corner Sectional",
          price: 5347,
          rating: 4.8,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(1)",
          product: "kajal",
          feature: "smudge",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 2,
          count: 1,
        },
        {
          image_url: "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202152/1334/dream-square-arm-upholstered-5-piece-u-shaped-sectional-2-l.jpg",
          name: "Dream Square Arm Upholstered U-Shaped Sectional",
          price: 6895,
          rating: 4.3,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 7,
          count: 1,
          reviews: "(49)",
          product: "combo",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202152/1331/dream-square-arm-slipcovered-modular-5-piece-u-shaped-sect-c.jpg",
          name: "Dream Square Arm Slipcovered U-Shaped Sectional",
          price: 7395,
          rating: 4.4,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(9)",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 5,
          count: 1,
          product: "",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202149/0540/build-your-own-dream-square-arm-upholstered-sectional-comp-1-l.jpg",
          name: "Build Your Own - Dream Square Arm Upholstered Sectional Components",
          price: 949,
          rating: 5,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(31)",
          product: "blush",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 10,
          count: 1,
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202151/0996/build-your-own-dream-square-arm-slipcovered-sectional-comp-1-l.jpg",
          name: "Build Your Own - Dream Square Arm Slipcovered Sectional Components",
          price: 1049,
          rating: 4.8,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(17)",
          product: "eye",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 4,
          count: 1,
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202152/0492/dream-square-arm-upholstered-armchair-4-l.jpg",
          name: "Dream Square Arm Upholstered Armchair",
          price: 1349,
          rating: 4.8,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(4)",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 20,
          count: 1,
          product: "liquid",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202144/0338/dream-square-arm-slipcovered-armchair-1-l.jpg",
          name: "Dream Square Arm Slipcovered Armchair",
          price: 1449,
          rating: 4.8,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(80)",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 15,
          count: 1,
          product: "primer",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202152/0495/dream-upholstered-sectional-ottoman-1-l.jpg",
          name: "Dream Upholstered Sectional Ottoman",
          price: 949,
          rating: 4.0,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          product: "eye",
          feature: "smudge",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 5,
          count: 1,
          reviews: "(10)",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202152/0918/dream-slipcovered-modular-sectional-ottoman-l.jpg",
          name: "Dream Slipcovered Modular Sectional Ottoman",
          price: 1049,
          rating: 4.8,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(59)",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 6,
          count: 1,
          product: "",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202151/1012/dream-upholstered-ottoman-2-l.jpg",
          name: "Dream Upholstered Ottoman",
          price: 749,
          rating: 4.7,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(43)",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 10,
          count: 1,
          product: "found",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202151/1117/dream-slipcovered-ottoman-1-c.jpg",
          name: "Dream Slipcovered Ottoman",
          price: 849,
          rating: 4.9,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(89)",
          shade_url: "https://i.ibb.co/855SYKc/white-bg.jpg",
          count: 1,
          product: "matte",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202151/0996/build-your-own-dream-square-arm-slipcovered-sectional-comp-1-l.jpg",
          name: "Dream Slipcovered Ottoman",
          price: 649,
          rating: 4.7,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(61)",
          shade_url: "https://i.ibb.co/855SYKc/white-bg.jpg",
          count: 1,
          product: "found",
        },
        {
          image_url:
            "https://assets.pbimgs.com/pbimgs/rk/images/dp/wcm/202151/1127/dream-square-arm-slipcovers-only-2-l.jpg",
          name: "Dream Square Arm Slipcovers Only",
          price: 499,
          rating: 4.9,
          star_url: "https://i.ibb.co/4d3n7ZC/star.png",
          reviews: "(45)",
          product: "blush",
          shade_url: "https://i.ibb.co/P4hFywk/ic-multiple-shades-opt2.png",
          shade_no: 2,
          count: 1,
        },
      ];
    
      localStorage.setItem("sofaData", JSON.stringify(sofaData));

}
export default sofaDataFn